
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo
  namespace: default
  labels:
    app/group: springboot-demo
    language: java
    app/profile: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app/group: springboot-demo
      language: java
      app/profile: prod
  template:
    metadata:
      labels:
        app/group: springboot-demo
        language: java
        app/profile: prod
    spec:
      containers:
      - name: server
        image: pydemia/springboot-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 5678
        env:
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "8000"
          - name: DEBUG_PORT
            value: "5678"
        resources:
          requests:
            memory: "500M"
            cpu: "200m"
          limits:
            memory: "1G"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-demo
  namespace: default
  labels:
    app/group: springboot-demo
    language: java
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app/group: springboot-demo
    language: java