# apiVersion: v1
# stringData:
#   .dockerconfigjson: ""
# kind: Secret
# metadata:
#   name: docker-cred
#   namespace: default
# type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
imagePullSecrets:
- name: docker-cred